"use client";

import { type ReactNode, useEffect, useState } from "react";
import { BarChart3, Download, Link2, Mic2, Package, RefreshCw, Sparkles, Upload, Video, Wand2 } from "lucide-react";
import type { ContentVariant, Product } from "@/lib/types";

type Analytics={productsImported:number;contentGenerated:number;rendersCompleted:number;publishStarted:number;publishCompleted:number;publishFailed:number};
type Health={ok:boolean;localAi:{ollama:{running:boolean;model:string};tts:{ready:boolean;model:string}}};
const localVoice="vi_VN-vais1000-medium";

export default function Home(){
 const [url,setUrl]=useState(""); const [name,setName]=useState(""); const [description,setDescription]=useState("");
 const [variants,setVariants]=useState(3); const [tone,setTone]=useState<"viral"|"review"|"educational"|"story">("viral");
 const [contents,setContents]=useState<ContentVariant[]>([]); const [selected,setSelected]=useState<ContentVariant|null>(null);
 const [videoUrl,setVideoUrl]=useState(""); const [jobId,setJobId]=useState(""); const [publishId,setPublishId]=useState("");
 const [privacy,setPrivacy]=useState("SELF_ONLY"); const [privacyOptions,setPrivacyOptions]=useState<string[]>(["SELF_ONLY"]);
 const [tiktokConnected,setTiktokConnected]=useState(false); const [voiceEnabled,setVoiceEnabled]=useState(true);
 const [health,setHealth]=useState<Health|null>(null); const [analytics,setAnalytics]=useState<Analytics|null>(null);
 const [status,setStatus]=useState(""); const [publishStatus,setPublishStatus]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{void refresh()},[]);
 async function refresh(){try{const [h,a,t]=await Promise.all([fetch("/api/health"),fetch("/api/analytics"),fetch("/api/tiktok/creator")]);if(h.ok)setHealth(await h.json());if(a.ok)setAnalytics(await a.json());if(t.ok){const td=await t.json();setTiktokConnected(Boolean(td.connected));const opts=Array.isArray(td.creator?.privacy_level_options)?td.creator.privacy_level_options:["SELF_ONLY"];setPrivacyOptions(opts.length?opts:["SELF_ONLY"]);}}catch{}}
 async function importProduct(){if(!url)return setStatus("Nhập Product URL trước.");setBusy(true);setStatus("Đang đọc sản phẩm…");try{const r=await fetch("/api/products/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Import thất bại");setName(d.product.name||"");setDescription(d.product.description||"");setStatus("Đã nhập sản phẩm.");await refresh()}catch(e){setStatus(e instanceof Error?e.message:"Import thất bại.")}finally{setBusy(false)}}
 async function generate(){const product:Product={id:crypto.randomUUID(),name:name||"Sản phẩm mới",url:url||undefined,description:description||"Chưa có mô tả",features:[],createdAt:new Date().toISOString()};setBusy(true);setStatus("Ollama đang viết nội dung local…");try{const r=await fetch("/api/content/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product,variants,tone})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Không thể tạo nội dung");setContents(d.variants);setSelected(d.variants[0]||null);setVideoUrl("");setStatus(`Đã tạo ${d.variants.length} biến thể bằng Ollama.`);await refresh()}catch(e){setStatus(e instanceof Error?e.message:"Tạo nội dung thất bại.")}finally{setBusy(false)}}
 async function render(){if(!selected)return setStatus("Chọn một content variant trước.");const product:Product={id:selected.productId,name:name||"Sản phẩm mới",url:url||undefined,description:description||"",features:[],createdAt:new Date().toISOString()};setBusy(true);setVideoUrl("");setStatus(voiceEnabled?"Piper đang tạo giọng đọc và Remotion đang render…":"Remotion đang render…");try{const r=await fetch("/api/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product,content:selected,voice:{enabled:voiceEnabled,name:localVoice,style:"giọng đọc tiếng Việt tự nhiên, rõ ràng, hơi nhanh"}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Render thất bại");setVideoUrl(d.videoUrl);setJobId(d.job.id);setStatus("Video local đã render xong.");await refresh()}catch(e){setStatus(e instanceof Error?e.message:"Render thất bại.")}finally{setBusy(false)}}
 async function publish(){if(!jobId||!selected)return setStatus("Render video trước.");if(!tiktokConnected){window.location.href="/api/tiktok/connect";return}if(!window.confirm("Bạn đã xem preview và xác nhận gửi video lên TikTok?"))return;setBusy(true);setPublishStatus("Đang upload…");try{const caption=`${selected.caption}\n\n${selected.hashtags.join(" ")}`.slice(0,2200);const r=await fetch("/api/tiktok/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId,caption,privacyLevel:privacy,confirm:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||"TikTok publish thất bại");setPublishId(d.publishId);setPublishStatus(`Publish ID: ${d.publishId}`);await refresh()}catch(e){setPublishStatus(e instanceof Error?e.message:"TikTok publish thất bại.")}finally{setBusy(false)}}
 async function checkPublish(){if(!publishId)return;setBusy(true);try{const r=await fetch("/api/tiktok/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({publishId})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPublishStatus(`Trạng thái: ${d.status?.status||"unknown"}${d.status?.fail_reason?` — ${d.status.fail_reason}`:""}`)}catch(e){setPublishStatus(e instanceof Error?e.message:"Không thể kiểm tra trạng thái")}finally{setBusy(false)}}
 return <main className="min-h-screen"><header className="border-b border-zinc-800 px-8 py-5 flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-white text-black p-2"><Sparkles size={20}/></div><div><div className="font-bold">Affiliate Studio</div><div className="text-xs text-zinc-500">Desktop • Local AI • No API key</div></div></div><div className="flex items-center gap-4 text-sm"><span className={health?.localAi.ollama.running?"text-emerald-400":"text-amber-400"}>{health?.localAi.ollama.running?"Ollama ready":"Ollama offline"}</span><span className={health?.localAi.tts.ready?"text-emerald-400":"text-amber-400"}>{health?.localAi.tts.ready?"Piper ready":"Piper not ready"}</span></div></header>
 <div className="mx-auto max-w-6xl px-6 py-10"><div className="max-w-3xl"><div className="text-xs tracking-[.2em] text-zinc-500">LOCAL AFFILIATE CONTENT ENGINE</div><h1 className="mt-3 text-5xl font-black tracking-tight">Tạo video affiliate <span className="text-zinc-500">ngay trên máy.</span></h1><p className="mt-4 text-lg leading-8 text-zinc-400">Ollama viết nội dung local → Piper đọc tiếng Việt → phụ đề → Remotion + FFmpeg render 9:16. Không cần Gemini API.</p></div>
 {analytics&&<section className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-6">{[["Products",analytics.productsImported],["Scripts",analytics.contentGenerated],["Renders",analytics.rendersCompleted],["Started",analytics.publishStarted],["Published",analytics.publishCompleted],["Failed",analytics.publishFailed]].map(([l,v])=><div className="card p-4" key={String(l)}><div className="text-xs text-zinc-500">{l}</div><div className="mt-2 text-xl font-bold">{v}</div></div>)}</section>}
 <section className="card mt-8 p-6"><div className="flex items-center gap-2 font-semibold"><Package size={18}/> Product</div><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="text-sm text-zinc-400">Product URL<div className="mt-2 flex gap-2"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." className="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 outline-none"/><button disabled={busy} onClick={importProduct} className="rounded-xl border border-zinc-700 px-4"><Link2 size={18}/></button></div></label><label className="text-sm text-zinc-400">Tên sản phẩm<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 outline-none"/></label><label className="text-sm text-zinc-400 md:col-span-2">Mô tả / điểm nổi bật<textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 outline-none"/></label></div></section>
 <section className="mt-4 grid gap-4 md:grid-cols-4"><Panel label="Variants"><select value={variants} onChange={e=>setVariants(Number(e.target.value))} className="mt-3 w-full rounded-lg bg-zinc-900 p-3"><option value={1}>1</option><option value={3}>3</option><option value={5}>5</option><option value={10}>10</option></select></Panel><Panel label="Angle"><select value={tone} onChange={e=>setTone(e.target.value as typeof tone)} className="mt-3 w-full rounded-lg bg-zinc-900 p-3"><option value="viral">Viral</option><option value="review">Review</option><option value="educational">Educational</option><option value="story">Story</option></select></Panel><Panel label="Voice"><div className="mt-3 flex items-center justify-between rounded-lg bg-zinc-900 p-3"><span className="text-sm">Piper Vietnamese</span><button onClick={()=>setVoiceEnabled(v=>!v)} className={voiceEnabled?"rounded bg-white p-2 text-black":"rounded border border-zinc-700 p-2 text-zinc-500"}><Mic2 size={17}/></button></div></Panel><div className="card flex flex-col justify-between p-5"><div><div className="text-sm text-zinc-500">Pipeline</div><div className="mt-2 font-semibold">Ollama → Piper → Remotion</div></div><button disabled={busy} onClick={generate} className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-semibold text-black disabled:opacity-50"><Wand2 size={17}/>{busy?"Working…":"Generate"}</button></div></section>
 {status&&<div className="mt-4 rounded-xl border border-zinc-800 p-4 text-sm text-zinc-300">{status}</div>}
 {contents.length>0&&<section className="mt-6 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="card p-6"><div className="flex items-center justify-between"><div className="font-semibold">Content variants</div><button onClick={generate} disabled={busy}><RefreshCw size={16}/></button></div><div className="mt-4 space-y-3">{contents.map((item,i)=><button key={item.id} onClick={()=>{setSelected(item);setVideoUrl("")}} className={`w-full rounded-xl border p-4 text-left ${selected?.id===item.id?"border-white bg-white/5":"border-zinc-800"}`}><div className="text-xs uppercase text-zinc-500">Variant {i+1} · {item.angle}</div><div className="mt-2 font-semibold">{item.hook}</div><div className="mt-2 line-clamp-3 text-sm text-zinc-400">{item.script}</div></button>)}</div></div><div className="card p-6"><div className="flex items-center justify-between"><div className="font-semibold">Video</div><div className="text-xs text-zinc-500">1080×1920</div></div>{selected?<><div className="mt-4 aspect-[9/16] max-h-[620px] overflow-hidden rounded-2xl border border-zinc-800 bg-black">{videoUrl?<video src={videoUrl} controls className="h-full w-full object-contain"/>:<div className="flex h-full items-center justify-center p-8 text-center text-zinc-500"><div><Video className="mx-auto mb-4"/><div>{selected.hook}</div><button onClick={render} disabled={busy} className="mt-5 rounded-xl bg-white px-5 py-3 font-semibold text-black">{busy?"Rendering…":"Render video"}</button></div></div>}</div>{videoUrl&&<><div className="mt-4 grid grid-cols-2 gap-3"><a href={videoUrl} download className="flex items-center justify-center gap-2 rounded-xl border border-zinc-700 px-4 py-3"><Download size={17}/>Download</a><button onClick={render} disabled={busy} className="flex items-center justify-center gap-2 rounded-xl border border-zinc-700 px-4 py-3"><RefreshCw size={17}/>Re-render</button></div><div className="mt-4 rounded-xl border border-zinc-800 p-4"><div className="flex items-center gap-2 font-medium"><Upload size={17}/> Optional TikTok</div>{!tiktokConnected?<button onClick={()=>{window.location.href="/api/tiktok/connect"}} className="mt-3 w-full rounded-xl bg-white px-4 py-3 font-semibold text-black">Connect TikTok</button>:<><select value={privacy} onChange={e=>setPrivacy(e.target.value)} className="mt-3 w-full rounded-lg bg-zinc-900 p-3">{privacyOptions.map(o=><option key={o}>{o}</option>)}</select><button onClick={publish} disabled={busy} className="mt-3 w-full rounded-xl bg-white px-4 py-3 font-semibold text-black">Confirm and publish</button>{publishId&&<button onClick={checkPublish} disabled={busy} className="mt-2 w-full rounded-xl border border-zinc-700 px-4 py-3">Check status</button>}{publishStatus&&<div className="mt-3 break-words text-xs text-zinc-400">{publishStatus}</div>}</>}</div></>}</>:<div className="mt-4 rounded-xl border border-dashed border-zinc-800 p-10 text-center text-zinc-500">Chọn content để render.</div>}</div></section>}
 <section className="mt-10 grid gap-4 md:grid-cols-3"><Feature icon={<Sparkles/>} title="Local AI" text={`Ollama ${health?.localAi.ollama.model||"qwen3:8b"} chạy ngay trên máy.`}/><Feature icon={<Mic2/>} title="Local Voice" text="Piper tạo giọng đọc tiếng Việt không cần cloud TTS."/><Feature icon={<BarChart3/>} title="Private by default" text="Kịch bản, audio, video và analytics được lưu trong thư mục dữ liệu của ứng dụng."/></section>
 </div></main>
}
function Panel({label,children}:{label:string;children:ReactNode}){return <div className="card p-5"><div className="text-sm text-zinc-500">{label}</div>{children}</div>}
function Feature({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="card p-5"><div className="text-zinc-400">{icon}</div><div className="mt-4 font-semibold">{title}</div><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p></div>}
